/* Real browser integration checks: no mocked scientific computation. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH || '../web/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),http=require('node:http');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.env.WEB_CHECK_OUTPUT || path.join(root,'outputs/web_validation'));
fs.mkdirSync(out,{recursive:true});
const checks=[],errors=[],requests=[];
const record=(name,detail)=>{checks.push({name,status:'passed',detail});console.log('PASS',name,JSON.stringify(detail));};
let server,browser,page;
async function waitIdle(){await page.waitForFunction(()=>!document.querySelector('#run-button').disabled,null,{timeout:300000});}
async function tab(kind,value){await page.locator(`[data-${kind}="${value}"]`).click();}
async function captureWorkspace(name){const size=page.viewportSize();await page.setViewportSize({width:1440,height:1600});await page.locator('.workspace-shell').scrollIntoViewIfNeeded();await page.locator('.workspace-shell').screenshot({path:path.join(out,name)});await page.setViewportSize(size);}
async function run(){await page.locator('#run-button').click();await waitIdle();assert.equal(await page.locator('#result-state').innerText(),'本次优化已完成',await page.locator('#run-status').innerText());}
async function settings(){await tab('config','settings');await page.locator('#population').fill('32');await page.locator('#population').blur();await page.locator('#generations').fill('10');await page.locator('#generations').blur();await page.locator('#runs').fill('1');await page.locator('#runs').blur();}
async function download(kind,name){await page.locator('#export-toggle').click();const promise=page.waitForEvent('download');await page.locator(`[data-export="${kind}"]`).click();const d=await promise;const file=path.join(out,name || d.suggestedFilename());await d.saveAs(file);await waitIdle();assert(fs.statSync(file).size>50);return file;}
async function csvRows(file){const content=fs.readFileSync(file,'utf8').replace(/^\ufeff/,'').trim().split(/\r?\n/);const split=s=>s.match(/("[^"]*(?:""[^"]*)*"|[^,]+)(,|$)/g).map(x=>x.replace(/,$/,'').replace(/^"|"$/g,'').replace(/""/g,'"'));const columns=split(content[0]);return content.slice(1).map(line=>Object.fromEntries(split(line).map((v,i)=>[columns[i],Number(v)])));}
(async()=>{
 let url=process.env.WEB_CHECK_URL;
 if(!url){server=http.createServer((req,res)=>{const requested=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const relative=requested==='/'?'index.html':requested.slice(1);const file=path.resolve(root,'web',relative);if(!file.startsWith(path.join(root,'web')+path.sep)){res.writeHead(403);res.end();return;}fs.readFile(file,(error,data)=>{if(error){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.py':'text/plain','.zip':'application/zip'})[path.extname(file)]||'application/octet-stream');res.end(data);});});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));url=`http://127.0.0.1:${server.address().port}/`;}
 browser=await chromium.launch({headless:true,...(process.env.WEB_BROWSER_EXECUTABLE?{executablePath:process.env.WEB_BROWSER_EXECUTABLE}:{})});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});let interrupted=false;
 await context.route(/\/scipy-[^/]+\.whl$/,async route=>{if(!interrupted){interrupted=true;await route.abort('failed');}else await route.continue();});
 page=await context.newPage();
 page.on('pageerror',error=>errors.push(error.message));page.on('request',req=>requests.push({method:req.method(),url:req.url()}));
 await page.goto(url,{waitUntil:'networkidle'});await page.waitForSelector('#main-chart svg');
 assert.equal(await page.locator('#result-state').innerText(),'合成示例预览');assert(await page.locator('#export-toggle').isDisabled());
 await page.screenshot({path:path.join(out,'desktop-home.png')});record('Preview is explicitly synthetic and cannot be exported',{});
 const candidateCounts={};
 for(const key of ['battery','exchanger','structure']){
   await page.locator('#example-select').selectOption(key);await settings();
   if(key==='battery'){await page.locator('#validation').selectOption('group');await page.locator('#group-column').selectOption('batch');await page.locator('#holdout-column').selectOption('batch');await page.locator('#holdout-value').fill('F');await page.locator('#holdout-value').blur();}
   await run();const config=JSON.parse(fs.readFileSync(await download('config',`${key}-configuration.json`),'utf8'));
   const rows=await csvRows(await download('csv',`${key}-candidates.csv`));assert(rows.length>0);candidateCounts[key]=rows.length;
   assert.equal(config.browser_runtime.platform,'emscripten');assert.equal(config.browser_runtime.pyodide,'0.29.3');assert.equal(Object.keys(config.browser_runtime.source_sha256).length,12);
   for(const row of rows){if(key==='battery'){assert(Number.isInteger(row.channels));assert(row.Tmax_K<=315+1e-8);const truth=320-5*row.flow_L_min-.45*row.channel_mm-.5*row.channels+.2*row.flow_L_min**2;assert(Math.abs(truth-row.Tmax_K)<1e-6);assert(truth<=315+1e-8);}if(key==='exchanger'){assert([2,4,6].includes(row.pitch_mm));assert(row.dp_Pa<=350+1e-8);assert(Math.abs(20+15*row.velocity_m_s**2+4*row.pitch_mm-row.dp_Pa)<1e-6);}if(key==='structure')assert(row.safety_margin>=-1e-8);}
   await tab('result','validation');assert(await page.locator('#metric-table tbody tr').count()>0);assert(await page.locator('#validation-chart circle').count()>0);
   if(key==='battery'){
     assert(interrupted);record('Interrupted dependency download recovers without reloading the page',{});
     assert.equal(config.sample_count,50);assert.equal(config.holdout_count,10);assert(await page.locator('#holdout-table tbody tr').count()>0);
     assert.equal(await page.locator('#validation-chart circle').count(),60);assert.equal(await page.locator('#residual-chart circle').count(),60);
     await page.locator('#validation-target').selectOption('pump_W');
     const rmse=await page.locator('#metric-table tbody tr').filter({hasText:'pump_W'}).locator('td').nth(3).innerText();
     assert.equal(await page.locator('#validation-scorecards strong').nth(1).innerText(),rmse);assert.match(await page.locator('#holdout-evidence').innerText(),/pump_W.*独立留出 10/);
     await page.locator('#validation-target').selectOption('Tmax_K');record('Per-response validation plots and scorecards match current engine records',{validation_points:50,holdout_points:10});
     await page.waitForTimeout(7100);await captureWorkspace('desktop-validation.png');
     assert.equal(await page.locator('#model option').count(),14);assert.equal(config.calculation_audit.training.fits_completed,18);assert.equal(config.calculation_audit.search.objective_vector_rows,992);
     await tab('result','matrix');assert.equal(await page.locator('#decision-matrix-table tbody tr').count(),rows.length);assert.match(await page.locator('#calculation-record').innerText(),/CFD 求解次数 0/);
     await page.locator('#plot-window-button').click();assert(await page.locator('#plot-lab').isVisible());assert.equal(await page.locator('#plot-canvas circle.point').count(),rows.length);assert.equal(await page.locator('#plot-canvas .recommended-point').count(),2);
     async function plotDownload(kind,name){assert(await page.locator('#plot-download-'+kind).isEnabled(),await page.locator('#plot-evidence').innerText());const [d]=await Promise.all([page.waitForEvent('download'),page.locator('#plot-download-'+kind).click()]);const file=path.join(out,name);await d.saveAs(file);return file;}
     const paper=await plotDownload('svg','paper-pareto.svg');assert(fs.readFileSync(paper,'utf8').includes('research-evidence'));assert(fs.readFileSync(paper,'utf8').includes('Times New Roman'));await page.locator('#plot-lab').screenshot({path:path.join(out,'paper-plot-window.png')});
     const png=await plotDownload('png','paper-pareto.png');const pngBytes=fs.readFileSync(png);assert.equal(pngBytes.subarray(1,4).toString(),'PNG');assert.equal(pngBytes.readUInt32BE(16),3000);
     await page.locator('#plot-type').selectOption('normalized');assert.equal(await page.locator('#plot-canvas circle').count(),rows.length*3);await plotDownload('svg','paper-normalized.svg');await plotDownload('png','paper-normalized.png');await page.locator('#plot-canvas').screenshot({path:path.join(out,'paper-normalized-preview.png')});
     const matrixFile=await plotDownload('json','paper-decision.json'),matrix=JSON.parse(fs.readFileSync(matrixFile,'utf8'));assert.equal(matrix.data.length,rows.length);for(const r of matrix.data){const c=config.target_names.reduce((sum,t,i)=>sum+config.normalized_weights[i]*r['有效损失::'+t]**2,0);assert(Math.abs(Math.sqrt(c)-r.D)<1e-12);assert(Math.abs(1/(1+r.D)-r.S_c)<1e-12);assert(Math.abs(r['效用复算差'])<1e-12);}
     record('Paper-style SVG/PNG and three-objective normalization use auditable engine matrices',{rows:matrix.data.length,python_fits:18,objective_vector_rows:992});
     await page.locator('#plot-type').selectOption('scatter');await page.locator('#plot-source').selectOption('decision_matrix');for(const [id,target] of [['x','Tmax_K'],['y','deltaT_K'],['color','pump_W']])await page.locator('#plot-'+id).selectOption('归一化::'+target);assert.equal(await page.locator('#plot-canvas circle.point').count(),rows.length);await plotDownload('png','paper-normalized-front.png');await plotDownload('svg','paper-normalized-front.svg');
     await page.locator('#plot-type').selectOption('correlation');const correlation=JSON.parse(fs.readFileSync(await plotDownload('json','paper-correlation.json'),'utf8'));assert.equal(correlation.correlation.training_rows,50);assert.equal(correlation.correlation.pairs[0][0],50);for(let i=0;i<correlation.correlation.columns.length;i++)assert(Math.abs(correlation.correlation.pearson[i][i]-1)<1e-12);await page.locator('#plot-canvas').screenshot({path:path.join(out,'paper-correlation-preview.png')});
     await page.locator('#plot-type').selectOption('convergence');const history=JSON.parse(fs.readFileSync(await plotDownload('json','paper-convergence.json'),'utf8'));assert.equal(history.data.length,10);assert.deepEqual(history.data.map(r=>r.generation),Array.from({length:10},(_,i)=>i+1));record('Correlation and per-generation records preserve training isolation and actual iterations',{training_rows:50,generations:10});
     const fieldPath=path.join(out,'synthetic-position-field.csv');fs.writeFileSync(fieldPath,'x_mm,y_mm,T_K\n0,0,300\n1,0,320\n0,1,285\n0.3,0.2,303\n');await page.locator('#plot-field-file').setInputFiles(fieldPath);await page.waitForFunction(()=>document.querySelector('#plot-field-status').textContent.includes('4 行'));await page.locator('#plot-resolution').fill('32');await page.locator('#plot-resolution').blur();await page.locator('#plot-field-compute').click();await page.waitForFunction(()=>!document.querySelector('#plot-field-compute').disabled,null,{timeout:300000});assert.match(await page.locator('#plot-field-status').innerText(),/4 个位置点/);const field=JSON.parse(fs.readFileSync(await plotDownload('json','paper-temperature.json'),'utf8'));assert.equal(field.data.length,1024);assert(field.spatial.masked_cells>0);for(const r of field.data.filter(r=>r.T_K!==null))assert(Math.abs(r.T_K-(300+20*r.x_mm-15*r.y_mm))<1e-8);await plotDownload('svg','paper-temperature.svg');await page.locator('#plot-canvas').screenshot({path:path.join(out,'paper-temperature-preview.png')});record('Spatial temperature interpolation reproduces a known plane and masks extrapolation',{grid:1024,masked:field.spatial.masked_cells});
     await plotDownload('png','paper-temperature.png');await page.locator('#plot-type').selectOption('score');assert.equal(await page.locator('#plot-canvas circle').count(),rows.length);await plotDownload('svg','paper-score.svg');await plotDownload('png','paper-score.png');await page.locator('#plot-type').selectOption('scatter');await page.locator('#plot-source').selectOption('input');const inputFigure=JSON.parse(fs.readFileSync(await plotDownload('json','paper-input.json'),'utf8'));assert.equal(inputFigure.data.length,60);assert.equal(await page.locator('#plot-canvas .recommended-point').count(),0);assert.match(await page.locator('#plot-canvas circle').first().locator('title').textContent(),/Input measurement/);
     await page.locator('#plot-close').click();await tab('result','validation');
     const workbook=await download('xlsx','browser-results.xlsx');assert.equal(fs.readFileSync(workbook).subarray(0,2).toString(),'PK');
     const project=await download('project','browser-project.optproj');const saved=JSON.parse(fs.readFileSync(project,'utf8'));assert.equal(saved.table.data.length,60);assert.equal(saved.problem.holdout_value,'F');
     await tab('result','overview');await download('svg','browser-tradeoff.svg');await tab('config','definition');await captureWorkspace('desktop-computed.png');
     assert.equal(await page.locator('#parallel-chart polyline').count(),8);await tab('result','diagnostics');assert.equal(await page.locator('#constraint-table tbody tr').count(),60);assert.equal(await page.locator('#run-table tbody tr').count(),1);assert.equal(await page.locator('#preference-table tbody tr').count(),10);assert.match(await page.locator('#run-interpretation').innerText(),/仅运行一次/);assert.equal(await page.locator('#coverage-chart circle').count(),rows.length);await captureWorkspace('desktop-diagnostics.png');record('Scientific diagnostics preserve input feasibility, coverage and preference records',{input_rows:60,preference_rows:10,candidate_lines:8});await tab('result','overview');
     await page.locator('#file-input').setInputFiles(project);await page.waitForFunction(()=>document.querySelector('#dataset-name').textContent.endsWith('.optproj'));
     assert(await page.locator('#export-toggle').isDisabled());assert.equal(await page.locator('#holdout-value').inputValue(),'F');await settings();await run();
     const repeated=await csvRows(await download('csv','battery-repeated.csv'));assert.deepEqual(repeated,rows);record('Project restoration reproduces candidates with fixed seed',rows.length);
   }
   record(`Real browser computation: ${key}`,{candidates:rows.length,model:config.selected_models,holdout:config.holdout_count});
   await tab('result','overview');
 }
 await page.locator('#example-select').selectOption('battery');await settings();await page.locator('#model').selectOption('RandomForest');await run();
 const forest=JSON.parse(fs.readFileSync(await download('config','forest-configuration.json'),'utf8'));assert(Object.values(forest.selected_models).every(x=>x==='RandomForest'));record('Forest estimators run without process spawning',forest.selected_models);
 await page.locator('#model').selectOption('RSM-Quadratic');await page.locator('#runs').fill('2');await page.locator('#runs').blur();await run();await tab('result','diagnostics');assert.equal(await page.locator('#run-table tbody tr').count(),2);assert.equal(await page.locator('#run-comparison-chart circle').count(),2);assert.match(await page.locator('#run-analysis-label').innerText(),/2 个实际随机种子/);record('Independent-run comparison shows actual distinct seed results',2);
 for(const model of ['Ridge-L2','ElasticNet','RSM-Cubic','KNN-Distance','AdaBoost']){await page.locator('#example-select').selectOption('exchanger');await settings();await page.locator('#model').selectOption(model);await page.locator('#decision').selectOption('IDEAL-COEFFICIENT');await run();const extra=JSON.parse(fs.readFileSync(await download('config',model+'-configuration.json'),'utf8'));assert(Object.values(extra.selected_models).every(n=>n===model));assert.equal(extra.calculation_audit.distance_formula,'sqrt(sum((w*delta)^2))');record('Additional browser model and coefficient-weighted decision: '+model,{fits:extra.calculation_audit.training.fits_completed});}
 await page.locator('#seed').fill('99');await page.locator('#seed').blur();assert(await page.locator('#export-toggle').isDisabled());assert.equal(await page.locator('#result-state').innerText(),'等待计算');assert.equal(await page.locator('#parallel-chart polyline').count(),0);assert.equal(await page.locator('#residual-chart circle').count(),0);assert.equal(await page.locator('#run-table tbody tr').count(),0);record('Configuration changes invalidate previous results and scientific views',{});
 await page.locator('#example-select').selectOption('exchanger');await tab('config','definition');await page.locator('[data-array="targets"][data-index="1"][data-property="role"]').selectOption('aux');await settings();await page.locator('#model').selectOption('Auto');await page.locator('#validation').selectOption('time');await page.locator('#time-column').selectOption('time');await page.locator('#folds').fill('3');await page.locator('#folds').blur();await tab('config','constraints');await page.locator('#domain').selectOption('hull');await run();const auto=JSON.parse(fs.readFileSync(await download('config','auto-time-configuration.json'),'utf8'));assert.equal(auto.responses[0].column,'dp_Pa');assert.equal(auto.cv_folds,3);assert.equal(auto.domain,'hull');await tab('result','validation');assert(await page.locator('#model-table tbody tr').count()>=16);record('Auto, forward validation, auxiliary responses and convex hull',auto.selected_models);
 await tab('config','settings');await page.locator('#validation').selectOption('group');await page.locator('#group-column').selectOption('batch');await page.locator('#folds').fill('20');await page.locator('#folds').blur();await page.locator('#run-button').click();await waitIdle();assert.match(await page.locator('#run-status').innerText(),/分组数少于折数/);assert(await page.locator('#export-toggle').isDisabled());record('Invalid validation configuration reports a recoverable error',{});
 await tab('result','data');const d=page.waitForEvent('download');await page.locator('#download-input').click();const input=await d;const inputFile=path.join(out,'import-data.csv');await input.saveAs(inputFile);await page.locator('#file-input').setInputFiles(inputFile);await waitIdle();assert.match(await page.locator('#dataset-info').innerText(),/60 个样本/);record('CSV data import',60);
 await page.locator('#file-input').setInputFiles(path.join(out,'browser-results.xlsx'));await waitIdle();assert(await page.locator('#sheet-picker').isVisible());assert(await page.locator('#sheet-select option').count()>=10);await page.locator('#sheet-select').selectOption({index:1});await waitIdle();record('Excel import and worksheet selection',await page.locator('#sheet-select option').count());
 await page.locator('#example-select').selectOption('battery');await settings();await tab('result','trace');const design=page.waitForEvent('download');await page.locator('#doe-button').click();const doe=await design;const doeFile=path.join(out,'browser-doe.csv');await doe.saveAs(doeFile);await waitIdle();assert.equal(fs.readFileSync(doeFile,'utf8').trim().split(/\r?\n/).length,34);record('Next experiment design exports 30 samples and 3 centres',33);
 await page.locator('#run-button').click();await page.locator('#cancel-button').click();await waitIdle();assert.match(await page.locator('#run-status').innerText(),/已取消/);assert(await page.locator('#export-toggle').isDisabled());record('Cancellation stops computation and invalidates results',{});
 await page.locator('#example-select').selectOption('exchanger');await tab('config','definition');await tab('result','overview');await page.waitForTimeout(7100);await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(out,'mobile-home.png')});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.locator('#workspace').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'mobile-workspace.png')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));record('Mobile layout has no horizontal overflow',{width:390});
 assert.equal(errors.length,0,errors.join('\n'));assert(requests.every(r=>['GET','HEAD'].includes(r.method)));record('No uncaught page errors or outgoing data requests',{page_errors:errors.length,requests:requests.length});
 fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({status:'passed',url,date:new Date().toISOString(),browser:await browser.version(),candidateCounts,checks},null,2));
})().catch(async error=>{console.error(error);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({status:'failed',checks,error:String(error),pageErrors:errors},null,2));if(page)await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});process.exitCode=1;}).finally(async()=>{await browser?.close();server?.close();});
